apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dranapaula-web
  namespace: est-web
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - dranapaulasou.com
    secretName: draanapaula-tls
  rules:
  - host: dranapaulasou.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dranapaula-web
            port:
              number: 80
