
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: draanapaula-web
  namespace: est-web
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - draanapaulasoubeauty.com
    secretName: draanapaula-tls
  rules:
  - host: draanapaulasoubeauty.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: draanapaula-web
            port:
              number: 80
